# [ SCSS6027 PORTAL CONFIG ]
title: SCSS6027_CUSTOMER_PORTAL
description: Project 4 Migration - Independent Data Vault
remote_theme: pages-themes/minimal@v0.2.0

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false

# Data Source Mapping
# We do NOT define a data_dir here because 
# the data is fetched LIVE from the FIREBASE repo via API.

# Exclusion list to keep the build clean
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _data/ # Just in case you have an empty folder there
